services:
  docker-linux:
    build: .
    container_name: root-linux
    mem_limit: 256m
    mem_reservation: 128m
    cpus: '0.5'
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "2222:22"
