services:
  docker-linux:
    image: alpine:latest  # or ubuntu:latest, debian:latest, etc.
    container_name: root-linux
    mem_limit: 256m
    mem_reservation: 128m
    cpus: '0.5'
    tty: true
    stdin_open: true
    restart: unless-stopped
