services:
  docker-linux:
    build: ./linux
    platform: linux/arm64  # change the platform to required
    image: ubuntu:24.04
    container_name: root-linux
    mem_limit: 256m
    mem_reservation: 128m
    cpus: '0.5'
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "2222:22"
    command: /usr/sbin/sshd -D  # This starts SSH in foreground