#alias amazon='xdg-open https://www.amazon.in/ &'

#Deal Finders

alias dl-grabon='firefox -P "ravi" https://www.grabon.in/ &'
alias dl-cashkaro='firefox -P "ravi" https://cashkaro.com/ &'
alias dl-coupondunia='firefox -P "ravi" https://www.coupondunia.in/ &'
alias dl-desidime='firefox -P "ravi" https://www.desidime.com/ &'
alias dl-freekaamaal='firefox -P "ravi" https://freekaamaal.com/ &'
alias dl-couponzguru='firefox -P "ravi" https://www.couponzguru.com/ &'
alias dl-paisawapas='firefox -P "ravi" https://www.paisawapas.com/ &'
alias dl-gopaisa='firefox -P "ravi" https://www.gopaisa.com/ &'
alias dl-zoutons='firefox -P "ravi" https://zoutons.com/ &'
alias dl-dealsmagnet='firefox -P "ravi" https://www.dealsmagnet.com/ &'
alias dl-99cashdeals='firefox -P "ravi" https://www.99cashdeals.com/ &'
alias dl-coupondeko='firefox -P "ravi" https://www.coupondeko.com/ &'
alias dl-neaarbuy='firefox -P "ravi" https://www.nearbuy.com/ &'
alias dl-savemoney='firefox -P "ravi" https://www.savemoney.in/ &'
alias dl-mydealz='firefox -P "ravi" https://www.mydealz.com/ &'

#Shopping sites

alias sh-amazon='firefox -P "ravi" https://www.amazon.in/ &'
alias sh-flipkart='firefox -P "ravi" https://www.flipkart.com/ &'
alias sh-bms='firefox -P "ravi" https://www.bookmyshow.com/ &'
alias sh-myntra='firefox -P "ravi" https://www.myntra.com/ &'
alias sh-meesho='firefox -P "ravi" https://www.meesho.com/ &'
alias sh-ajio='firefox -P "ravi" https://www.ajio.com/ &'
alias sh-nykaa='firefox -P "ravi" https://www.nykaa.com/ &'
alias sh-jiomart='firefox -P "ravi" https://www.jiomart.com/ &'
alias sh-bigbasket='firefox -P "ravi" https://www.bigbasket.com/ &'
alias sh-snapdeal='firefox -P "ravi" https://www.snapdeal.com/ &'
alias sh-tatacliq='firefox -P "ravi" https://www.tatacliq.com/ &'
alias sh-shopify='firefox -P "ravi" https://www.shopify.com/in &'
alias sh-indiamart='firefox -P "ravi" https://www.indiamart.com/ &'
alias sh-lenskart='firefox -P "ravi" https://www.lenskart.com/ &'
alias sh-croma='firefox -P "ravi" https://www.croma.com/ &'

#Travel Sites
alias tr-irctc='firefox -P "ravi" https://www.irctc.co.in/ &'
alias tr-makemytrip='firefox -P "ravi" https://www.makemytrip.com/ &'
alias tr-skyscanner='firefox -P "ravi" https://www.skyscanner.co.in/ &'
alias tr-redbus='firefox -P "ravi" https://www.redbus.in/ &'
alias tr-ba='firefox -P "ravi" https://www.britishairways.com/ &'
alias tr-yatra='firefox -P "ravi" https://www.yatra.com/ &'
alias tr-cleartrip='firefox -P "ravi" https://www.cleartrip.com/ &'
alias tr-easemytrip='firefox -P "ravi" https://www.easemytrip.com/ &'
alias tr-goibibo='firefox -P "ravi" https://www.goibibo.com/ &'
alias tr-ixigo='firefox -P "ravi" https://www.ixigo.com/ &'
alias tr-thomascook='firefox -P "ravi" https://www.thomascook.in/ &'
alias tr-sotc='firefox -P "ravi" https://www.sotc.in/ &'
alias tr-travelguru='firefox -P "ravi" https://www.travelguru.com/ &'
alias tr-via='firefox -P "ravi" https://www.via.com/ &'
alias tr-akbar='firefox -P "ravi" https://www.akbartravels.com/ &'

#Accomodation Sites
alias ac-booking='firefox -P "ravi" https://www.booking.com/ &'
alias ac-airbnb='firefox -P "ravi" https://www.airbnb.co.in/ &'
alias ac-oyo='firefox -P "ravi" https://www.oyorooms.com/ &'
alias ac-agoda='firefox -P "ravi" https://www.agoda.com/ &'
alias ac-goibibo='firefox -P "ravi" https://www.goibibo.com/hotels/ &'
alias ac-makemytrip='firefox -P "ravi" https://www.makemytrip.com/hotels/ &'
alias ac-cleartrip='firefox -P "ravi" https://www.cleartrip.com/hotels &'
alias ac-trivago='firefox -P "ravi" https://www.trivago.in/ &'
alias ac-expedia='firefox -P "ravi" https://www.expedia.com/ &'
alias ac-priceline='firefox -P "ravi" https://www.priceline.com/ &'
