#alias amazon='xdg-open https://www.amazon.in/ &'

#Deal Finders

alias dl-grabon='/apps/firefox/firefox -P ravi -no-remote https://www.grabon.in/ &'
alias dl-cashkaro='/apps/firefox/firefox -P ravi -no-remote https://cashkaro.com/ &'
alias dl-coupondunia='/apps/firefox/firefox -P ravi -no-remote https://www.coupondunia.in/ &'
alias dl-desidime='/apps/firefox/firefox -P ravi -no-remote https://www.desidime.com/ &'
alias dl-freekaamaal='/apps/firefox/firefox -P ravi -no-remote https://freekaamaal.com/ &'
alias dl-couponzguru='/apps/firefox/firefox -P ravi -no-remote https://www.couponzguru.com/ &'
alias dl-paisawapas='/apps/firefox/firefox -P ravi -no-remote https://www.paisawapas.com/ &'
alias dl-gopaisa='/apps/firefox/firefox -P ravi -no-remote https://www.gopaisa.com/ &'
alias dl-zoutons='/apps/firefox/firefox -P ravi -no-remote https://zoutons.com/ &'
alias dl-dealsmagnet='/apps/firefox/firefox -P ravi -no-remote https://www.dealsmagnet.com/ &'
alias dl-99cashdeals='/apps/firefox/firefox -P ravi -no-remote https://www.99cashdeals.com/ &'
alias dl-coupondeko='/apps/firefox/firefox -P ravi -no-remote https://www.coupondeko.com/ &'
alias dl-neaarbuy='/apps/firefox/firefox -P ravi -no-remote https://www.nearbuy.com/ &'
alias dl-savemoney='/apps/firefox/firefox -P ravi -no-remote https://www.savemoney.in/ &'
alias dl-mydealz='/apps/firefox/firefox -P ravi -no-remote https://www.mydealz.com/ &'

#Shopping sites

alias sh-amazon='/apps/firefox/firefox -P ravi -no-remote https://www.amazon.in/ &'
alias sh-flipkart='/apps/firefox/firefox -P ravi -no-remote https://www.flipkart.com/ &'
alias sh-bms='/apps/firefox/firefox -P ravi -no-remote https://www.bookmyshow.com/ &'
alias sh-myntra='/apps/firefox/firefox -P ravi -no-remote https://www.myntra.com/ &'
alias sh-meesho='/apps/firefox/firefox -P ravi -no-remote https://www.meesho.com/ &'
alias sh-ajio='/apps/firefox/firefox -P ravi -no-remote https://www.ajio.com/ &'
alias sh-nykaa='/apps/firefox/firefox -P ravi -no-remote https://www.nykaa.com/ &'
alias sh-jiomart='/apps/firefox/firefox -P ravi -no-remote https://www.jiomart.com/ &'
alias sh-bigbasket='/apps/firefox/firefox -P ravi -no-remote https://www.bigbasket.com/ &'
alias sh-snapdeal='/apps/firefox/firefox -P ravi -no-remote https://www.snapdeal.com/ &'
alias sh-tatacliq='/apps/firefox/firefox -P ravi -no-remote https://www.tatacliq.com/ &'
alias sh-shopify='/apps/firefox/firefox -P ravi -no-remote https://www.shopify.com/in &'
alias sh-indiamart='/apps/firefox/firefox -P ravi -no-remote https://www.indiamart.com/ &'
alias sh-lenskart='/apps/firefox/firefox -P ravi -no-remote https://www.lenskart.com/ &'
alias sh-croma='/apps/firefox/firefox -P ravi -no-remote https://www.croma.com/ &'

#Travel Sites
alias tr-irctc='/apps/firefox/firefox -P ravi -no-remote https://www.irctc.co.in/ &'
alias tr-makemytrip='/apps/firefox/firefox -P ravi -no-remote https://www.makemytrip.com/ &'
alias tr-skyscanner='/apps/firefox/firefox -P ravi -no-remote https://www.skyscanner.co.in/ &'
alias tr-redbus='/apps/firefox/firefox -P ravi -no-remote https://www.redbus.in/ &'
alias tr-ba='/apps/firefox/firefox -P ravi -no-remote https://www.britishairways.com/ &'
alias tr-yatra='/apps/firefox/firefox -P ravi -no-remote https://www.yatra.com/ &'
alias tr-cleartrip='/apps/firefox/firefox -P ravi -no-remote https://www.cleartrip.com/ &'
alias tr-easemytrip='/apps/firefox/firefox -P ravi -no-remote https://www.easemytrip.com/ &'
alias tr-goibibo='/apps/firefox/firefox -P ravi -no-remote https://www.goibibo.com/ &'
alias tr-ixigo='/apps/firefox/firefox -P ravi -no-remote https://www.ixigo.com/ &'
alias tr-thomascook='/apps/firefox/firefox -P ravi -no-remote https://www.thomascook.in/ &'
alias tr-sotc='/apps/firefox/firefox -P ravi -no-remote https://www.sotc.in/ &'
alias tr-travelguru='/apps/firefox/firefox -P ravi -no-remote https://www.travelguru.com/ &'
alias tr-via='/apps/firefox/firefox -P ravi -no-remote https://www.via.com/ &'
alias tr-akbar='/apps/firefox/firefox -P ravi -no-remote https://www.akbartravels.com/ &'

#Accomodation Sites
alias ac-booking='/apps/firefox/firefox -P ravi -no-remote https://www.booking.com/ &'
alias ac-airbnb='/apps/firefox/firefox -P ravi -no-remote https://www.airbnb.co.in/ &'
alias ac-oyo='/apps/firefox/firefox -P ravi -no-remote https://www.oyorooms.com/ &'
alias ac-agoda='/apps/firefox/firefox -P ravi -no-remote https://www.agoda.com/ &'
alias ac-goibibo='/apps/firefox/firefox -P ravi -no-remote https://www.goibibo.com/hotels/ &'
alias ac-makemytrip='/apps/firefox/firefox -P ravi -no-remote https://www.makemytrip.com/hotels/ &'
alias ac-cleartrip='/apps/firefox/firefox -P ravi -no-remote https://www.cleartrip.com/hotels &'
alias ac-trivago='/apps/firefox/firefox -P ravi -no-remote https://www.trivago.in/ &'
alias ac-expedia='/apps/firefox/firefox -P ravi -no-remote https://www.expedia.com/ &'
alias ac-priceline='/apps/firefox/firefox -P ravi -no-remote https://www.priceline.com/ &'
